### ISSUE TITLE
bug: mDNS Daemon Panics When Parsing DNS Records

### ISSUE THREAD

**Issue by HamzaAlsarakbi** [keepsimple1/mdns-sd#290]
the mDNS daemon thread panics as it's parsing DNS records.

## Stacktrace

```log
thread 'mDNS_daemon' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/mdns-sd-0.12.0/src/dns_parser.rs:1795:34:
index out of bounds: the len is 265 but the index is 265
thread 'stack backtrace:
mDNS_daemon' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/mdns-sd-0.12.0/src/dns_parser.rs:1795:34:
index out of bounds: the len is 265 but the index is 265
   0: rust_begin_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_bounds_check
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:180:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/slice/index.rs:261:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/slice/index.rs:18:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/alloc/src/vec/mod.rs:2728:9
   6: mdns_sd::dns_parser::DnsIncoming::read_type_bitmap
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/mdns-sd-0.12.0/src/dns_parser.rs:1795:34
   7: mdns_sd::dns_parser::DnsIncoming::read_rr_records
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/mdns-sd-0.12.0/src/dns_parser.rs:1742:25
   8: mdns_sd::dns_parser::DnsIncoming::read_additional
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/mdns-sd-0.12.0/src/dns_parser.rs:1616:27
   9: mdns_sd::dns_parser::DnsIncoming::new
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/mdns-sd-0.12.0/src/dns_parser.rs:1532:9
  10: mdns_sd::service_daemon::Zeroconf::handle_read
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/mdns-sd-0.12.0/src/service_daemon.rs:1594:15
  11: mdns_sd::service_daemon::ServiceDaemon::handle_poller_events
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/mdns-sd-0.12.0/src/service_daemon.rs:463:19
  12: mdns_sd::service_daemon::ServiceDaemon::run
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/mdns-sd-0.12.0/src/service_daemon.rs:524:26
  13: mdns_sd::service_daemon::ServiceDaemon::daemon_thread
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/mdns-sd-0.12.0/src/service_daemon.rs:423:28
  14: mdns_sd::service_daemon::ServiceDaemon::new::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/mdns-sd-0.12.0/src/service_daemon.rs:189:28
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: rust_begin_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_bounds_check
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:180:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/slice/index.rs:261:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/slice/index.rs:18:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/alloc/src/vec/mod.rs:2728:9
   6: mdns_sd::dns_parser::DnsIncoming::read_type_bitmap
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/mdns-sd-0.12.0/src/dns_parser.rs:1795:34
   7: mdns_sd::dns_parser::DnsIncoming::read_rr_records
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/mdns-sd-0.12.0/src/dns_parser.rs:1742:25
   8: mdns_sd::dns_parser::DnsIncoming::read_additional
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/mdns-sd-0.12.0/src/dns_parser.rs:1616:27
   9: mdns_sd::dns_parser::DnsIncoming::new
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/mdns-sd-0.12.0/src/dns_parser.rs:1532:9
  10: mdns_sd::service_daemon::Zeroconf::handle_read
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/mdns-sd-0.12.0/src/service_daemon.rs:1594:15
  11: mdns_sd::service_daemon::ServiceDaemon::handle_poller_events
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/mdns-sd-0.12.0/src/service_daemon.rs:463:19
  12: mdns_sd::service_daemon::ServiceDaemon::run
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/mdns-sd-0.12.0/src/service_daemon.rs:524:26
  13: mdns_sd::service_daemon::ServiceDaemon::daemon_thread
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/mdns-sd-0.12.0/src/service_daemon.rs:423:28
  14: mdns_sd::service_daemon::ServiceDaemon::new::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/mdns-sd-0.12.0/src/service_daemon.rs:189:28
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

## Debug Log

```log
[2024-12-12T05:42:35Z DEBUG mdns_sd::dns_parser] read_rr_records: DnsNSec { record: DnsRecord { entry: DnsEntry { name: "hothoney-15817.local.", ty: NSEC, class: 1, cache_flush: true }, ttl: 4500, created: 1733982155509, expires: 1733986655509, refresh: 1733985755509, new_name: None }, next_domain: "hothoney-15817.local.", type_bitmap: [64, 0, 0, 8] }
[2024-12-12T05:42:35Z DEBUG mdns_sd::dns_parser] read_rr_records: DnsNSec { record: DnsRecord { entry: DnsEntry { name: "hothoney-15817.local.", ty: NSEC, class: 1, cache_flush: true }, ttl: 4500, created: 1733982155510, expires: 1733986655510, refresh: 1733985755510, new_name: None }, next_domain: "hothoney-15817.local.", type_bitmap: [64, 0, 0, 8] }
[2024-12-12T05:42:35Z DEBUG mdns_sd::dns_parser] read_rr_records: DnsNSec { record: DnsRecord { entry: DnsEntry { name: "hothoney (177568)._companion-link._tcp.local.", ty: NSEC, class: 1, cache_flush: true }, ttl: 4500, created: 1733982155510, expires: 1733986655510, refresh: 1733985755510, new_name: None }, next_domain: "hothoney (177568)._companion-link._tcp.local.", type_bitmap: [0, 0, 128, 0, 64] }
[2024-12-12T05:42:35Z DEBUG mdns_sd::dns_parser] read_rr_records: DnsNSec { record: DnsRecord { entry: DnsEntry { name: "hothoney (177568)._companion-link._tcp.local.", ty: NSEC, class: 1, cache_flush: true }, ttl: 4500, created: 1733982155510, expires: 1733986655510, refresh: 1733985755510, new_name: None }, next_domain: "hothoney (177568)._companion-link._tcp.local.", type_bitmap: [0, 0, 128, 0, 64] }
[2024-12-12T05:42:35Z DEBUG mdns_sd::service_daemon] handle_response: 4 answers 0 authorities 2 additionals
[2024-12-12T05:42:35Z DEBUG mdns_sd::service_daemon] handle_response: 4 answers 0 authorities 2 additionals
[2024-12-12T05:42:35Z DEBUG mdns_sd::service_daemon] received 265 bytes at IP: 10.125.20.1
[2024-12-12T05:42:35Z DEBUG mdns_sd::service_daemon] received 265 bytes at IP: 172.100.0.1
[2024-12-12T05:42:35Z DEBUG mdns_sd::dns_parser] read_header: id 0, 0 questions 4 answers 0 authorities 2 additionals
[2024-12-12T05:42:35Z DEBUG mdns_sd::dns_parser] read_header: id 0, 0 questions 4 answers 0 authorities 2 additionals
[2024-12-12T05:42:35Z DEBUG mdns_sd::dns_parser] read_questions: 0
[2024-12-12T05:42:35Z DEBUG mdns_sd::dns_parser] read_questions: 0
[2024-12-12T05:42:35Z DEBUG mdns_sd::dns_parser] read_rr_records: 4
[2024-12-12T05:42:35Z DEBUG mdns_sd::dns_parser] read_rr_records: 4
[2024-12-12T05:42:35Z DEBUG mdns_sd::dns_parser] read_rr_records: DnsAddress { record: DnsRecord { entry: DnsEntry { name: "mozza-23737.local.", ty: AAAA, class: 1, cache_flush: true }, ttl: 4500, created: 1733982155510, expires: 1733986655510, refresh: 1733985755510, new_name: None }, address: fe80::1053:5e7c:4803:2fa }
[2024-12-12T05:42:35Z DEBUG mdns_sd::dns_parser] read_rr_records: DnsAddress { record: DnsRecord { entry: DnsEntry { name: "mozza-23737.local.", ty: AAAA, class: 1, cache_flush: true }, ttl: 4500, created: 1733982155510, expires: 1733986655510, refresh: 1733985755510, new_name: None }, address: fe80::1053:5e7c:4803:2fa }
[2024-12-12T05:42:35Z DEBUG mdns_sd::dns_parser] read_rr_records: DnsAddress { record: DnsRecord { entry: DnsEntry { name: "mozza-23737.local.", ty: A, class: 1, cache_flush: true }, ttl: 4500, created: 1733982155510, expires: 1733986655510, refresh: 1733985755510, new_name: None }, address: 10.48.20.112 }
[2024-12-12T05:42:35Z DEBUG mdns_sd::dns_parser] read_rr_records: DnsAddress { record: DnsRecord { entry: DnsEntry { name: "mozza-23737.local.", ty: A, class: 1, cache_flush: true }, ttl: 4500, created: 1733982155511, expires: 1733986655511, refresh: 1733985755511, new_name: None }, address: 10.48.20.112 }
[2024-12-12T05:42:35Z DEBUG mdns_sd::dns_parser] read_rr_records: DnsTxt { record: DnsRecord { entry: DnsEntry { name: "mozza (88318)._companion-link._tcp.local.", ty: TXT, class: 1, cache_flush: true }, ttl: 4500, created: 1733982155511, expires: 1733986655511, refresh: 1733985755511, new_name: None }, text: [TxtProperty {key: "rpBA", val: Some("3A:D0:E7:FB:FA:51")}, TxtProperty {key: "rpAD", val: Some("f5f484c421f5")}, TxtProperty {key: "rpFl", val: Some("0x20000")}, TxtProperty {key: "rpHN", val: Some("ba391581c830")}, TxtProperty {key: "rpMac", val: Some("0")}, TxtProperty {key: "rpVr", val: Some("580.4")}] }
[2024-12-12T05:42:35Z DEBUG mdns_sd::dns_parser] read_rr_records: DnsTxt { record: DnsRecord { entry: DnsEntry { name: "mozza (88318)._companion-link._tcp.local.", ty: TXT, class: 1, cache_flush: true }, ttl: 4500, created: 1733982155511, expires: 1733986655511, refresh: 1733985755511, new_name: None }, text: [TxtProperty {key: "rpBA", val: Some("3A:D0:E7:FB:FA:51")}, TxtProperty {key: "rpAD", val: Some("f5f484c421f5")}, TxtProperty {key: "rpFl", val: Some("0x20000")}, TxtProperty {key: "rpHN", val: Some("ba391581c830")}, TxtProperty {key: "rpMac", val: Some("0")}, TxtProperty {key: "rpVr", val: Some("580.4")}] }
[2024-12-12T05:42:35Z DEBUG mdns_sd::dns_parser] read_rr_records: DnsSrv { record: DnsRecord { entry: DnsEntry { name: "mozza (88318)._companion-link._tcp.local.", ty: SRV, class: 1, cache_flush: true }, ttl: 4500, created: 1733982155511, expires: 1733986655511, refresh: 1733985755511, new_name: None }, priority: 0, weight: 0, host: "mozza-23737.local.", port: 50432 }
[2024-12-12T05:42:35Z DEBUG mdns_sd::dns_parser] read_rr_records: DnsSrv { record: DnsRecord { entry: DnsEntry { name: "mozza (88318)._companion-link._tcp.local.", ty: SRV, class: 1, cache_flush: true }, ttl: 4500, created: 1733982155511, expires: 1733986655511, refresh: 1733985755511, new_name: None }, priority: 0, weight: 0, host: "mozza-23737.local.", port: 50432 }
[2024-12-12T05:42:35Z DEBUG mdns_sd::dns_parser] read_rr_records: 0
[2024-12-12T05:42:35Z DEBUG mdns_sd::dns_parser] read_rr_records: 0
[2024-12-12T05:42:35Z DEBUG mdns_sd::dns_parser] read_rr_records: 2
[2024-12-12T05:42:35Z DEBUG mdns_sd::dns_parser] read_rr_records: 2
[2024-12-12T05:42:35Z DEBUG mdns_sd::dns_parser] read_rr_records: DnsNSec { record: DnsRecord { entry: DnsEntry { name: "mozza-23737.local.", ty: NSEC, class: 1, cache_flush: true }, ttl: 4500, created: 1733982155511, expires: 1733986655511, refresh: 1733985755511, new_name: None }, next_domain: "mozza-23737.local.", type_bitmap: [64, 0, 0, 8] }
[2024-12-12T05:42:35Z DEBUG mdns_sd::dns_parser] read_rr_records: DnsNSec { record: DnsRecord { entry: DnsEntry { name: "mozza-23737.local.", ty: NSEC, class: 1, cache_flush: true }, ttl: 4500, created: 1733982155511, expires: 1733986655511, refresh: 1733985755511, new_name: None }, next_domain: "mozza-23737.local.", type_bitmap: [64, 0, 0, 8] }
```

**Comment by keepsimple1** [comment]
Thanks for opening this issue!  I've posted a PR #291  to check the data length in this case. I'm wondering if this is indeed a corrupt NSEC record incoming, or is it a valid record but we are not able to process it properly?

**Comment by HamzaAlsarakbi** [comment]
I just pulled from your merged PR and I'm testing at the moment. The crash happens 30-40 hours in so we'll see in a day or two.
As if this is a corrupt NSEC record, I'm not entirely sure, sorry :/

**Comment by HamzaAlsarakbi** [comment]
So I've run it for a couple of days and there have been no crashes so far. Thanks a lot for the fix :)

**Comment by keepsimple1** [comment]
thanks for confirming! I will close the issue now.
